DROP TABLE IF EXISTS game_x_genre;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS global_seq CASCADE;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE game
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    developer   VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX game_unique_name_and_developer_idx ON game (name, developer);

CREATE TABLE genre
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name        VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX genre_unique_name_idx ON genre (name);

CREATE TABLE game_x_genre
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    game_id     INTEGER NOT NULL REFERENCES game(id),
    genre_id    INTEGER NOT NULL REFERENCES genre(id)
);
CREATE UNIQUE INDEX game_x_genre_unique_game_id_and_genre_id_idx ON game_x_genre (game_id, genre_id);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name       VARCHAR(255)            NOT NULL,
    email      VARCHAR(255)            NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    registered TIMESTAMP DEFAULT now() NOT NULL,
    enabled    BOOLEAN   DEFAULT TRUE  NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);